### ISSUE TITLE
I get a tailored question based on previous conversations

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#34]
Check if the user has said what their least favourite subject(s) is and what date(s) they have this subject. If we have this information, on the day(s) they have this subject, ask them a specific question related to that subject and how they are feeling. 

- [x] check database for least favourite subject(s) and date(s)
- [x] Compare with current date of conversation
- [x] Add tailored question to list of essential questions if data matches
