### ISSUE TITLE
I can see more details per conversation so I can start spotting trends

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/nightingale#35]
Pull out more information from each conversation and display in an Activities / Chart section
  - [ ] Good experiences per conversation
  - [ ] Negative experiences per conversation
  - [ ] My daily mood (chart)
